
- name: Sample playbook calling a collection
  hosts: all
  roles:
    - samplerole
  collections:
    - bdf.smoketest
  tasks:
    - name: Say Hello
      debug:
        msg: "Hello"
    - name: Import role from collection
      import_role:
        name: test-role
   # - name: Import Single role **not in collection**
   #   import_role:
   #     name: samplerole
       
